### PR TITLE
initcap support

### LINKED ISSUE #1177: [FEA] Support INITCAP for strings
I'd like to be able to use INITCAP to capitalize the first character of every "token" in a string. This is listed as a supported operation on string columns in the Calcite reference, but is currently not implemented.

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
​
​
# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()
​
# bc = BlazingContext()
​
​
df = pd.DataFrame({
    "a": ["this is", "an example", "of sql"],
    "b": [10, 9, 8],
})
​
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    INITCAP(a)
FROM df
"""
​
spark.sql(query).show()
​
print(bc.explain(query))
# print(bc.sql(query)) # fails
+----------+----------+
|         a|initcap(a)|
+----------+----------+
|   this is|   This Is|
|an example|An Example|
|    of sql|    Of Sql|
+----------+----------+

LogicalProject(a=[$0], EXPR$1=[INITCAP($0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a, EXPR$1]])

```

### PR DESCRIPTION
**Pull request by derekmorr**
This closes #1177 .

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by williamBlazing** [comment]
add to whitelist

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by williamBlazing** [comment]
Hello @derekmorr thanks for working on this. You will need to add this PR to the CHANGELOG.md file for our CI tests to run.

Additionally, could you please add some end to end tests where you combine `initcap` with other operations. For example:

query = """select o_orderkey, INITCAP(SUBSTRING(o_comment, 1, 5)) || SUBSTRING(INITCAP(o_comment, 0, 5)) from orders
                    where o_orderkey < 10000"""

**Comment by williamBlazing** [comment]
@derekmorr We have entered code freeze for version 0.17, which means this feature will be bumped to 0.18.
Also, I have updated our Contribution guidelines. I hope they explain better how we do things. If you think they need more information please reach out.

**Comment by derekmorr** [comment]
No worries. I've been a bit busy during the week lately, so I only have time to work on this over the weekend. I'll update the PR soon.

**Comment by williamBlazing** [comment]
@derekmorr Sorry, this PR was closed by mistake. It seems like you have the setting activated for branchs being deleted when a PR is merged or deleted, which means the branch was deleted. You should be able to restore it from your github. I sincerely hope your work was not lost. 
Please create the PR again when you get a chance, this time pointing at 0.18

**Comment by derekmorr** [comment]
I'm having trouble getting 0.18 building on my dev machine. I keep getting errors concerning rmm:

```
[ 41%] Building CUDA object CMakeFiles/blazingsql-engine.dir/src/communication/messages/MessageUtil.cu.o
/home/ubuntu/anaconda3/envs/bsql/blazingsql/engine/src/communication/messages/MessageUtil.cu(30): error: namespace "rmm" has no member "exec_policy"

/home/ubuntu/anaconda3/envs/bsql/blazingsql/engine/src/communication/messages/MessageUtil.cu(30): error: no instance of overloaded function "thrust::transform" matches the argument list
            argument types are: (<error-type>, int32_t *, int32_t *, int32_t *, lambda [](int32_t)->int)

2 errors detected in the compilation of "/tmp/tmpxft_00002eca_00000000-8_MessageUtil.compute_75.cpp1.ii".
CMakeFiles/blazingsql-engine.dir/build.make:783: recipe for target 'CMakeFiles/blazingsql-engine.dir/src/communication/messages/MessageUtil.cu.o' failed
make[2]: *** [CMakeFiles/blazingsql-engine.dir/src/communication/messages/MessageUtil.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:518: recipe for target 'CMakeFiles/blazingsql-engine.dir/all' failed
make[1]: *** [CMakeFiles/blazingsql-engine.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```

I've created a clean conda environment and pulled in the nightly dependencies, but I still get the same error. Any advice?

**Pull request closed without merging**
