### PR TITLE
[REVIEW] Partitioned data test

### LINKED ISSUE #1295: Create Partitioned Data Tests
We will want to test the following combinations:

- Tests with csv, parquet and orc files
- Tests with different types of `create_table` statements:
1. create_table allowing for auto inference:
bc.create_table('table_name','root_directory_of_table_folders', file_format='parquet')

2. create_table manually specifying everything, but including **all partitions**:
bc.create_table('asia_transactions2', location, 
                file_format='parquet', 
                partitions = {'t_year':[2017, 2018], 
                              't_company_id':[2, 4, 6], 
                              'region': ['asia']}, 
                partitions_schema = [('t_year','int'),
                                     ('t_company_id','int'),
                                     ('region','str')])

3.  create_table manually specifying everything, but including  only some of the partitions:
bc.create_table('asia_transactions2', location, 
                file_format='parquet', 
                partitions = {'t_year':[2017], 
                              't_company_id':[2, 4], 
                              'region': ['asia']}, 
                partitions_schema = [('t_year','int'),
                                     ('t_company_id','int'),
                                     ('region','str')])

NOTE: for this scenario you would have to validate against an alternate version of the query since it will have less data
For example:
bsql_query = "select * from asia_transactions2 order by t_company_id"
validation_query = "select * from asia_transactions2 where t_year = 2017 and t_company_id in (2, 4) order by t_company_id"
How do you do this?
When creating a test and using `runTest.run_query(...)` use the parameter: `query_spark` . see timestampdiffTest.py for example usage.

Things to consider when creating these tests:
- We may want to not do all tables. I would suggest only using customer and orders (or more likely bool_orders)
- We will want to have partitions on data of type strings, int and bool  (this is in bool_orders)
- Ideas for what columns to partition:
-        customer - n_nationkey, c_mktsegment
-        orders - o_orderpriority
-         orders - boolean column (o_confirmed)

Note for create_table for csv, you may need to pass in other parameters such as column names and types.

### PR DESCRIPTION
**Pull request by diegodfrf**
Fixes #1295

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by diegodfrf** [comment]
rerun-tests

**Comment by diegodfrf** [comment]
fixes #1399

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by diegodfrf** [comment]
rerun-tests

**Pull request merged**
