### PR TITLE
[REVIEW] Creating a gdf_column with col name

### PR DESCRIPTION
**Pull request by Christian8491**

### CODE REVIEW

**Comment by kharoc** [comment]
1 RAL

*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1092/1128
FAILED: 36/1128
CRASH: 0/1128
TOTAL: 1128
*******************************************************************************
!!!!!!!!!!!!!!!! FAILED gdf TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - gdf
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - gdf
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED psv TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - psv
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - psv
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED parquet TESTS !!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Coalesce Test - parquet
    FAILED: 1/11 ['TEST_12']
    CRASH: 0/11
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Inner join Test - parquet
    FAILED: 4/16 ['TEST_01A', 'TEST_01B', 'TEST_01C', 'TEST_03']
    CRASH: 0/16
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Nested Queries Test - parquet
    FAILED: 1/4 ['TEST_02']
    CRASH: 0/4
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - parquet
    FAILED: 6/10 ['TEST_01', 'TEST_06', 'TEST_09', 'TEST_10', 'TEST_11', 'TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Simple Distribution From Local Test - parquet
    FAILED: 1/52 ['TEST_35']
    CRASH: 0/52
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - parquet
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED orc TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Date Test - orc
    FAILED: 2/5 ['TEST_01', 'TEST_02']
    CRASH: 0/5
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Timestamp Test - orc
    FAILED: 1/12 ['TEST_02']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Non-EquiJoin Queries Test - orc
    FAILED: 2/8 ['TEST_01', 'TEST_02']
    CRASH: 0/8
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Limit Test - orc
    FAILED: 1/10 ['TEST_07']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Bindable Alias Test - orc
    FAILED: 1/12 ['TEST_09']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Simple Distribution From Local Test - orc
    FAILED: 4/52 ['TEST_22', 'TEST_43', 'TEST_46', 'TEST_49']
    CRASH: 0/52
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - orc
    FAILED: 6/11 ['TEST_03', 'TEST_05', 'TEST_06', 'TEST_10', 'TEST_14', 'TEST_15', 'TEST_18']
    CRASH: 0/11
!!!!!!!!!!!!!!!! FAILED dask_cudf TESTS !!!!!!!!!!!!!!!!
MAX DELTA: 36.0
*******************************************************************************

2 Worker's

===================================================
INFO:
INFO:Coalesce Test $$0_0$$ dask_cudf
INFO:TEST_12
INFO:SELECT COALESCE(l.l_shipinstruct, o.o_orderstatus) FROM lineitem l inner join orders o on l.l_orderkey = o.o_orderkey where o.o_totalprice < 1574.23
ERROR:Success
ERROR:
WARNING:1
WARNING:1
WARNING:2
=============== New query: TEST_13 =================
client: tcp://127.0.0.1:19437
Client: No data inside message.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007faea5ec97e0, pid=10955, tid=0x00007fadf4ffd700
#
# JRE version: OpenJDK Runtime Environment (8.0_192-b01) (build 1.8.0_192-b01)
# Java VM: OpenJDK 64-Bit Server VM (25.192-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x16c7e0]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/kharoly/blazingsql/logtest/hs_err_pid10955.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
distributed.nanny - WARNING - Restarting worker

**Comment by Christian8491** [comment]
Commits before `Fixes predicatesWithNulls Tests 01 & Test 05 - parquet`  are to solve the error: `NameError: duplicated column name ''`. Those solve tests as columnBasis and substrings and also the reported by @mario21ic issue #238

**Comment by Christian8491** [comment]
Close #238

**Comment by kharoc** [comment]
1 Ral


*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1098/1128
FAILED: 30/1128
CRASH: 0/1128
TOTAL: 1128
*******************************************************************************
!!!!!!!!!!!!!!!! FAILED gdf TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - gdf
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
!!!!!!!!!!!!!!!! FAILED psv TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - psv
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - psv
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED parquet TESTS !!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Nested Queries Test - parquet
    FAILED: 1/4 ['TEST_02']
    CRASH: 0/4
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - parquet
    FAILED: 6/10 ['TEST_01', 'TEST_06', 'TEST_09', 'TEST_10', 'TEST_11', 'TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Simple Distribution From Local Test - parquet
    FAILED: 1/52 ['TEST_35']
    CRASH: 0/52
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - parquet
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED orc TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Date Test - orc
    FAILED: 2/5 ['TEST_01', 'TEST_02']
    CRASH: 0/5
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Timestamp Test - orc
    FAILED: 1/12 ['TEST_02']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Non-EquiJoin Queries Test - orc
    FAILED: 2/8 ['TEST_01', 'TEST_02']
    CRASH: 0/8
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Limit Test - orc
    FAILED: 1/10 ['TEST_07']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Bindable Alias Test - orc
    FAILED: 1/12 ['TEST_09']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Simple Distribution From Local Test - orc
    FAILED: 4/52 ['TEST_22', 'TEST_43', 'TEST_46', 'TEST_49']
    CRASH: 0/52
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - orc
    FAILED: 6/11 ['TEST_03', 'TEST_05', 'TEST_06', 'TEST_10', 'TEST_14', 'TEST_15', 'TEST_18']
    CRASH: 0/11
!!!!!!!!!!!!!!!! FAILED dask_cudf TESTS !!!!!!!!!!!!!!!!
MAX DELTA: 36.0
*******************************************************************************

2 Workers

*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1324/1346
FAILED: 22/1346
CRASH: 0/1346
TOTAL: 1346
*******************************************************************************
!!!!!!!!!!!!!!!! FAILED gdf TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - gdf
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
!!!!!!!!!!!!!!!! FAILED psv TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - psv
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
!!!!!!!!!!!!!!!! FAILED parquet TESTS !!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Case Test - parquet
    FAILED: 1/10 ['TEST_13']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - parquet
    FAILED: 0/12 ['TEST_15']
    CRASH: 0/12
!!!!!!!!!!!!!!!! FAILED orc TESTS !!!!!!!!!!!!!!!!
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Date Test - orc
    FAILED: 2/5 ['TEST_01', 'TEST_02']
    CRASH: 0/5
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Timestamp Test - orc
    FAILED: 1/12 ['TEST_02']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Non-EquiJoin Queries Test - orc
    FAILED: 2/8 ['TEST_01', 'TEST_02']
    CRASH: 0/8
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Limit Test - orc
    FAILED: 1/10 ['TEST_07']
    CRASH: 0/10
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Bindable Alias Test - orc
    FAILED: 1/12 ['TEST_09']
    CRASH: 0/12
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: Simple Distribution From Local Test - orc
    FAILED: 4/52 ['TEST_22', 'TEST_43', 'TEST_46', 'TEST_49']
    CRASH: 0/52
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    SUMMARY for FAILED test suite: TPCH Queries Test - orc
    FAILED: 6/11 ['TEST_03', 'TEST_05', 'TEST_06', 'TEST_10', 'TEST_14', 'TEST_15', 'TEST_18']
    CRASH: 0/11
!!!!!!!!!!!!!!!! FAILED dask_cudf TESTS !!!!!!!!!!!!!!!!
MAX DELTA: 432.0
*******************************************************************************

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Pull request merged**
