### PR TITLE
added update to version for gcp

### PR DESCRIPTION
**Pull request by mario21ic**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mario21ic** [comment]
rerun tests

**Comment by romulo-auccapuclla** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by williamBlazing** [comment]
@mario21ic what is the dependencies.sh file? what is it meant to do? I notice that the cuda version and the python version are both hardcoded, which is concerning.

**Comment by mario21ic** [comment]
> @mario21ic what is the dependencies.sh file? what is it meant to do? I notice that the cuda version and the python version are both hardcoded, which is concerning.

The file dependencies.sh was for avoiding forgetting some dependencies, but it could be a way to install our dependencies on the local environment. In a next PR I will add some arguments to be more flexible.

**Pull request merged**
