### PR TITLE
[REVIEW] Improving message error for invalid or unsupported expressions

### LINKED ISSUE #1069: Trying to run a window function query throws confusing error.
This query:
SELECT o_custkey, o_orderpriority, 
SUM(o_totalprice) OVER 
(PARTITION BY o_custkey ORDER BY o_orderdate ROWS BETWEEN 5 PRECEDING AND CURRENT ROW ) from orders

Has this relational algebra:
LogicalProject(o_custkey=[$0], o_orderpriority=[$1], EXPR$2=[CASE(>(COUNT($2) OVER (PARTITION BY $0 ORDER BY $3 ROWS 5 PRECEDING), 0), $SUM0($2) OVER (PARTITION BY $0 ORDER BY $3 ROWS 5 PRECEDING), null:DOUBLE)])
  BindableTableScan(table=[[main, orders]], projects=[[1, 5, 3, 4]], aliases=[[o_custkey, o_orderpriority, EXPR$2]])

Which throws this error:
In Projection kernel batch 0 for LogicalProject(o_custkey=[$0], o_orderpriority=[$1], EXPR$2=[CASE(>(COUNT($2) OVER (PARTITION BY $0 ORDER BY $3 ROWS 5 PRECEDING), 0), $SUM0($2) OVER (PARTITION BY $0 ORDER BY $3 ROWS 5 PRECEDING), null:DOUBLE)]). What: Ral failure at: /home/william/miniconda3/envs/bsql/blazingsql/engine/src/parser/expression_utils.cpp:290: Unsupported operator: COUNT

We should detect window functions type syntax in relational algebra and throw a more appropriate error

### PR DESCRIPTION
**Pull request by rommelDB**
Fixes #1069

### CODE REVIEW

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Review by felipeblazing — APPROVED** [review]

**Pull request merged**
