### PR TITLE
[REVIEW] Add ConfigOptionsTest

### LINKED ISSUE #1089: e2e tests with different configuration options
We want to take a standard set of queries to run and change the different config_options to different settings to force slightly different things to happen in the engine and therefore test some different edge cases and make sure nothing breaks.

For the standard set of queries to run, we should use the tpch queries. We can take the `tpchQueriesTest.py` copy it and edit it for our purposes. Since we are re-using a set of queries, we can also re-use the results to test against, therefore that needs to be taken into consideration. The `queryType` passed into `run_query` i think will need to be the same, so that it knows what result set to pull to compare against. But in the beginning of the script, it should show that it IS a different E2E test. Something like:
```print("==============================")
    print("config_options Test")
    print("Test set: " + str(setInd) + " Options: " + str(config_options_set[setInd]))
    print("==============================")
```
Where we express that its the config_options Test, not tpchQueriesTest and we also say which config_options set is running.

For the test, we will run the same queries over and over, but with different config_options sets. For each config_option set, we should create a new BlazingContext, which means that the BlazingContext created will need to go out of scope between sets and the tables will need to be re-created each time.

The sets that we should test for are as follows:
SET 1:
JOIN_PARTITION_SIZE_THRESHOLD = 10
MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE=10
TABLE_SCAN_KERNEL_NUM_THREADS=3
MAX_KERNEL_RUN_THREADS=5

SET 2:
JOIN_PARTITION_SIZE_THRESHOLD = 10
MAX_DATA_LOAD_CONCAT_CACHE_BYTE_SIZE=10
TABLE_SCAN_KERNEL_NUM_THREADS=1
MAX_KERNEL_RUN_THREADS=1

SET 3:
MAX_NUM_ORDER_BY_PARTITIONS_PER_NODE = 1
NUM_BYTES_PER_ORDER_BY_PARTITION=10

SET 4:
ORDER_BY_SAMPLES_RATIO=0.99
MAX_ORDER_BY_SAMPLES_PER_NODE=5
MAX_SEND_MESSAGE_THREADS=1
TRANSPORT_BUFFER_BYTE_SIZE=10000
TRANSPORT_POOL_NUM_BUFFERS=10000

SET 5:
ORDER_BY_SAMPLES_RATIO=0.99
MAX_ORDER_BY_SAMPLES_PER_NODE=5000000
MAX_SEND_MESSAGE_THREADS=200
TRANSPORT_BUFFER_BYTE_SIZE=10000
TRANSPORT_POOL_NUM_BUFFERS=10

SET 6:
ORDER_BY_SAMPLES_RATIO=0.00001
MAX_ORDER_BY_SAMPLES_PER_NODE=5
MAX_SEND_MESSAGE_THREADS=200
TRANSPORT_BUFFER_BYTE_SIZE=100000000
TRANSPORT_POOL_NUM_BUFFERS=10

SET 7:
ORDER_BY_SAMPLES_RATIO=0.00001
MAX_ORDER_BY_SAMPLES_PER_NODE=5000000
MAX_SEND_MESSAGE_THREADS=1
TRANSPORT_BUFFER_BYTE_SIZE=100000000
TRANSPORT_POOL_NUM_BUFFERS=100

SET 8:
BLAZING_DEVICE_MEM_CONSUMPTION_THRESHOLD=0.0001
MEMORY_MONITOR_PERIOD=5000000

### PR DESCRIPTION
**Pull request by Christian8491**
This PR closes #1089

### CODE REVIEW

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun-tests

**Pull request merged**
