### PR TITLE
[REVIEW] Folder refactor

### PR DESCRIPTION
**Pull request by rommelDB**
Reorganizing some files, according to https://github.com/BlazingDB/blazingsql/issues/1131

- Creating new folders: blazing_table, cache_machine, execution_graph and execution_kernels
- Moving related files to their corresponding folder

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rommelDB** [comment]
rerun tests

**Comment by williamBlazing** [comment]
I dont like having `execution_graph/logic_controllers/execution_graph`.
In general, i think we should flatten things a little more. This is what i would propose:
`src/execution_graph/logic_controllers/execution_graph` becomes `src/execution_graph` 
`src/execution_graph/logic_controllers/blazing_table` becomes `src/blazing_table` 
`src/execution_graph/logic_controllers/cache_machine` becomes `src/cache_machine` 
`src/execution_graph/logic_controllers/execution_kernels` becomes `src/execution_kernels`   

And `src/execution_graph/Context.*` would still be in `src/execution_graph/Context.*`

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Pull request merged**
