### PR TITLE
[REVIEW] Enable MySQL-specific SQL operators in addition to Standard and Oracle

### LINKED ISSUE #1178: [FEA] Enable dialect-specific operators with CalciteConnectionProperty
Calcite [supports](https://calcite.apache.org/docs/reference.html#dialect-specific-operators) a variety of useful operators that are not in the SQL standard.

It appears these can be enabled by setting the `FUN` parameter of CalciteConnectionProperty for the connection.

https://calcite.apache.org/docs/adapter.html#jdbc-connect-string-parameters

This is necessary for:
- https://github.com/BlazingDB/blazingsql/issues/1173
- https://github.com/BlazingDB/blazingsql/issues/1174
- https://github.com/BlazingDB/blazingsql/issues/1176

### PR DESCRIPTION
**Pull request by beckernick**
This PR:
- Enables MySQL-specific SQL operators, which makes several useful string operators potentially available (REVERSE, LEFT, RIGHT, etc.). Currently only Standard SQL and Oracle SQL are available.

I've confirmed that this change does allow Calcite to use these operators. Passes `./test.sh` locally.

This closes #1178 

```python
from blazingsql import BlazingContext
import pandas as pd

bc = BlazingContext()​
​
df = pd.DataFrame({
    "a": ["one", "two"],
    "b": [1, 2],
})
​
bc.create_table("df", df)
​
query = """
SELECT
    a,
    REVERSE(a)
FROM df
"""

print(bc.explain(query))
LogicalProject(a=[$0], EXPR$1=[REVERSE($0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a, EXPR$1]])

```

### CODE REVIEW

**Comment by felipeblazing** [comment]
@beckernick have you checked to see that you can actually run those queries. i do not believe we have reverse implemented as a function so that would need to be done first.

**Comment by beckernick** [comment]
> @beckernick have you checked to see that you can actually run those queries. i do not believe we have reverse implemented as a function so that would need to be done first.

Yep, we're aligned. That will be implemented in a separate PR that closes #1173

**Comment by williamBlazing** [comment]
Ideally we should see if there are any operators that are implemented in the different SQL standards that have the same keyword, but with different APIs. I am not sure if we know of any in particular but if we do, it would be useful to know how Calcite would handle this situation

**Comment by williamBlazing** [comment]
rerun-tests

**Pull request merged**
