### PR TITLE
[REVIEW] Improve test script for blazingsql-testing-file

### LINKED ISSUE #1474: Change blazingsql-testing-files to have the same naming conventions
If a developer needs to add or modify an end to end test in the blazingsql repo, then they need to make changes to the testing files in the  blazingsql-testing-files repo via a PR. That PR branch must be on their fork and must have the same branch name as the branch from their PR. 

We need to update test.sh which makes a checkout/clone of blazingsql-testing-files. Before doing that checkout/clone the script should see if a branch exists on the PR author's fork that has the same name as the PR's branch. If that branch exists, then the checkout/clone should be for that branch, otherwise it should be for the blazingsql-testing-files branch that matches the target of the PR in blazingsql, meaning branch-0.X. 

We also need to therefore make sure blazingsql-testing-files also has a branch for matching version for different blazing branches e.g. for branch-0.19, branch-0.20 and we need to keep it up to date with whatever the latest branch is

### PR DESCRIPTION
**Pull request by mario21ic**
This PR fixes #1474

In this job
https://gpuci.gpuopenanalytics.com/job/blazingsql/job/gpuci/job/blazingsql/job/prb/job/blazingsql-gpu-build/2810/consoleText the branch was https://github.com/blazingdb/blazingsql-testing-files/tree/feat/master

Then I made a fork from https://github.com/blazingdb/blazingsql-testing-files 
After that, this job https://gpuci.gpuopenanalytics.com/job/blazingsql/job/gpuci/job/blazingsql/job/prb/job/blazingsql-gpu-build/2813/consoleText cloned the repo from https://github.com/mario21ic/blazingsql-testing-files/tree/feat/data-branch

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by mario21ic** [comment]
rerun tests

**Comment by mario21ic** [comment]
rerun tests

**Comment by williamBlazing** [comment]
@mario21ic we actually dont want to use the master branch.
We want to use `branch-0.20` in this case. Or a branch with the same name as the target branch of the PR.
So if the PR is targeting `branch-0.20` then it should try to use a `branch-0.20` in blazingsql-testing-files
if the PR is targeting `branch-0.21` then it should try to use a `branch-0.21` in blazingsql-testing-files, ... etc
You will need to create the `branch-0.20` in blazingsql-testing-files in the BlazingDB fork for this to work

**Comment by mario21ic** [comment]
rerun tests

**Comment by mario21ic** [comment]
rerun tests

**Comment by mario21ic** [comment]
rerun tests

**Review by williamBlazing — APPROVED** [review]

**Comment by mario21ic** [comment]
The repository **blazingsql-testing-files** is cloned from the user's fork branch. Otherwise, the default branch to clone is **branch-0.20** which will be changed according to new releases.

**Pull request merged**
