### PR TITLE
[REVIEW] Fix pre compiler flags for sql parsers

### PR DESCRIPTION
**Pull request by aucahuasi**

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by williamBlazing** [comment]
rerun-tests

**Review by felipeblazing — APPROVED** [review]

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by williamBlazing** [comment]
rerun-tests

**Pull request merged**
