### PR TITLE
[REVIEW] Removing cudf dependency as a thirdparty code

### LINKED ISSUE #1042: Remove dependency on thirdparty/cudf. Remove dependency on gtest when building without tests
We should no longer need to have cudf as a third party because of this https://github.com/rapidsai/cudf/pull/6201

Also tu support the efforts that are part of https://github.com/BlazingDB/blazingsql/pull/1040 we should remove gtest as a dependency when building without unit tests

### PR DESCRIPTION
**Pull request by rommelDB**
Closes partially #1042

### CODE REVIEW

**Comment by rommelDB** [comment]
rerun tests

**Comment by romeluko** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Pull request merged**
