### PR TITLE
[REVIEW] Implement string REVERSE

### LINKED ISSUE #1173: [FEA] Support REVERSE for strings
I'd like to be able to call REVERSE on a string column to reverse every string. This is listed as a supported operation on string columns in the Calcite [reference](https://calcite.apache.org/docs/reference.html#string), but it may need to be enabled based on [this](https://calcite.apache.org/docs/reference.html#dialect-specific-operators) segment of the docs describing Dialect specific operators.

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
​
​
# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()
​
# bc = BlazingContext()
​
​
df = pd.DataFrame({
    "a": ["Felipe", "William", "Rodrigo"],
    "b": [10, 9, 8],
})
​
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    REVERSE(a)
FROM df
"""
​
spark.sql(query).show()
​
print(bc.explain(query)) # Fails
+-------+----------+
|      a|reverse(a)|
+-------+----------+
| Felipe|    epileF|
|William|   mailliW|
|Rodrigo|   ogirdoR|
+-------+----------+
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getRelationalAlgebraString()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getRelationalAlgebra()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getNonOptimizedRelationalAlgebra()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.validateQuery()

Exception: Java Exception

The above exception was the direct cause of the following exception:

com.blazingdb.calcite.application.SqlValidationExceptionTraceback (most recent call last)
/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/pyblazing/apiv2/context.py in explain(self, sql)
   1693         try:
-> 1694             algebra = self.generator.getRelationalAlgebraString(sql)
   1695 

com.blazingdb.calcite.application.SqlValidationException: com.blazingdb.calcite.application.SqlValidationException: No match found for function signature REVERSE(<CHARACTER>)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-19-98a9ae652764> in <module>
     29 spark.sql(query).show()
     30 
---> 31 print(bc.explain(query))
     32 # print(bc.sql(query)) # hangs

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/pyblazing/apiv2/context.py in explain(self, sql)
   1696         except SqlValidationExceptionClass as exception:
   1697             # jpype.JException as exception:
-> 1698             raise Exception(exception.message())
   1699             # algebra = ""
   1700             # print("SQL Parsing Error")

Exception: No match found for function signature REVERSE(<CHARACTER>)
```

### PR DESCRIPTION
**Pull request by beckernick**
This PR:
- [x] Implements the REVERSE unary operator for string columns using cudf::strings::slice_strings
- [x] Adds a new end-to-end test in stringsTests.py, ~and updates the runTest.py~ seems like this PR doesn't need to update the runTest
- [x] Passes tests locally
- [x] PR to update testing files

This closes #1173 

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd

# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()

# bc = BlazingContext()


df = pd.DataFrame({
    "a": ["Felipe", "William", "Rodrigo"],
    "b": [10, 9, 8],
})

bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    REVERSE(a) as reversed_a
FROM df
"""

spark.sql(query).show()
print(bc.sql(query))

+-------+----------+
|      a|reversed_a|
+-------+----------+
| Felipe|    epileF|
|William|   mailliW|
|Rodrigo|   ogirdoR|
+-------+----------+

         a reversed_a
0   Felipe     epileF
1  William    mailliW
2  Rodrigo    ogirdoR

```

### CODE REVIEW

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by beckernick** [comment]
https://github.com/BlazingDB/blazingsql-testing-files/pull/3

**Comment by williamBlazing** [comment]
@beckernick could you please modify this PR so that your tests 12 and 13 become 14 and 15, and similarly update https://github.com/BlazingDB/blazingsql-testing-files/pull/3

This is because it will clash with the TRIM PR, which i will merge first. https://github.com/BlazingDB/blazingsql/pull/1201 Thanks

**Comment by beckernick** [comment]
Yes, I'll update the PRs. Would it perhaps be worth exploring a test naming convention that reduces the likelihood of name collisions? I could imagine this kind of implicit merge conflict on tests coming up frequently in the future

**Comment by beckernick** [comment]
Updated tests: https://github.com/BlazingDB/blazingsql-testing-files/pull/4

**Comment by williamBlazing** [comment]
rerun tests

**Pull request merged**
