### PR TITLE
[REVIEW] Fixing uninitialized variable in orc metadata and handling their exceptions properly

### LINKED ISSUE #1334: [BUG] Some ORC files cannot be opened on debug mode
**Describe the bug**
Opening some ORC files in debug mode crashes the engine.

Current log:
```
cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1611726397735/work/cpp/src/table/table.cpp:42: Column size mismatch: 0 != 1
cio.ParseSchemaError: [ParseSchema Error] cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1611726397735/work/cpp/src/table/table.cpp:42: Column size mismatch: 0 != 1
Exception ignored in: 'cio.parseMetadataPython'
cio.ParseSchemaError: [ParseSchema Error] cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1611726397735/work/cpp/src/table/table.cpp:42: Column size mismatch: 0 != 1

[rommelbz:6431 :0:6431] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x10)
==== backtrace (tid:   6431) ====
 0  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/./libucs.so.0(ucs_handle_error+0x115) [0x7f93a00abee5]
 1  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/./libucs.so.0(+0x26281) [0x7f93a00ac281]
 2  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/./libucs.so.0(+0x26452) [0x7f93a00ac452]
 3  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/jre/lib/amd64/server/libjvm.so(+0x9323f4) [0x7f93964e13f4]
 4  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/jre/lib/amd64/server/libjvm.so(JVM_handle_linux_signal+0x9d) [0x7f93964e928d]
 5  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/jre/lib/amd64/server/libjvm.so(+0x92ec73) [0x7f93964ddc73]
 6  /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390) [0x7f94988a3390]
 7  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/python3.7/site-packages/cio.cpython-37m-x86_64-linux-gnu.so(_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EEaSERKS7_+0x1a) [0x7f93a0366e9a]
 8  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/python3.7/site-packages/cio.cpython-37m-x86_64-linux-gnu.so(+0x583d9) [0x7f93a03453d9]
 9  /home/rommel/miniconda3/envs/blazingsqlonly-sources-270121/lib/python3.7/site-packages/cio.cpython-37m-x86_64-linux-gnu.so(+0x5a7f4) [0x7f93a03477f4]
10  python(_PyMethodDef_RawFastCallKeywords+0x274) [0x55863714c914]
11  python(_PyCFunction_FastCallKeywords+0x21) [0x55863714ca31]
12  python(_PyEval_EvalFrameDefault+0x4e1d) [0x5586371b8ebd]
13  python(_PyFunction_FastCallKeywords+0xfb) [0x55863714be7b]
14  python(_PyEval_EvalFrameDefault+0x6a0) [0x5586371b4740]
15  python(_PyEval_EvalCodeWithName+0xc30) [0x5586370fc160]
16  python(_PyFunction_FastCallKeywords+0x387) [0x55863714c107]
17  python(_PyEval_EvalFrameDefault+0x6a0) [0x5586371b4740]
18  python(_PyEval_EvalCodeWithName+0x2f9) [0x5586370fb829]
19  python(PyEval_EvalCodeEx+0x44) [0x5586370fc714]
20  python(PyEval_EvalCode+0x1c) [0x5586370fc73c]
21  python(+0x22cf14) [0x558637213f14]
22  python(PyRun_FileExFlags+0xa1) [0x55863721e331]
23  python(PyRun_SimpleFileExFlags+0x1c3) [0x55863721e523]
24  python(+0x238655) [0x55863721f655]
25  python(_Py_UnixMain+0x3c) [0x55863721f77c]
26  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f94984e8840]
27  python(+0x1dcff0) [0x5586371c3ff0]
=================================
Segmentation fault (core dumped)

```

### PR DESCRIPTION
**Pull request by rommelDB**
Fixes #1334

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Pull request merged**
