### PR TITLE
[REVIEW] Add support for INITCAP

### LINKED ISSUE #1177: [FEA] Support INITCAP for strings
I'd like to be able to use INITCAP to capitalize the first character of every "token" in a string. This is listed as a supported operation on string columns in the Calcite reference, but is currently not implemented.

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
​
​
# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()
​
# bc = BlazingContext()
​
​
df = pd.DataFrame({
    "a": ["this is", "an example", "of sql"],
    "b": [10, 9, 8],
})
​
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    INITCAP(a)
FROM df
"""
​
spark.sql(query).show()
​
print(bc.explain(query))
# print(bc.sql(query)) # fails
+----------+----------+
|         a|initcap(a)|
+----------+----------+
|   this is|   This Is|
|an example|An Example|
|    of sql|    Of Sql|
+----------+----------+

LogicalProject(a=[$0], EXPR$1=[INITCAP($0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a, EXPR$1]])

```

### PR DESCRIPTION
**Pull request by Christian8491**
This PR is based on #1260. Thanks @derekmorr for the great work implementing this feature. This PR closes #1177

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by derekmorr** [comment]
Thanks for this. I got slammed at work and didn't have time to revist the PR.

**Comment by Christian8491** [comment]
rerun tests

**Pull request merged**
