### PR TITLE
[REVIEW] Update cmake cuda std to version17

### PR DESCRIPTION
**Pull request by romulo-auccapuclla**
Changes
1. Update engine cmake to support cuda std version 17

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by williamBlazing** [comment]
add-to-whitelist

**Comment by williamBlazing** [comment]
add to whitelist

**Comment by williamBlazing** [comment]
ok to test

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Pull request closed without merging**
