### PR TITLE
[REVIEW] Fix metadata mistmatch 

### LINKED ISSUE #1023: [BUG] Metadata mismatch in parseMetadata
**Describe the bug**
Bug happens with multiple nodes and parquet files when creating a table. 
The issue happens with edge case data where:
some parquet files have some columns that are all nulls  and other files do have data in those columns

create_table fails with the following error:

```ValueError                                Traceback (most recent call last)
<ipython-input-61-c7ef4711cd0c> in <module>
----> 1 bc.create_table("tst",files[3:5],file_format="parquet")

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/pyblazing/apiv2/context.py in create_table(self, table_name, input, **kwargs)
   1901 
   1902                 if isinstance(parsedMetadata, dask_cudf.core.DataFrame):
-> 1903                     parsedMetadata = parsedMetadata.compute()
   1904                     parsedMetadata = parsedMetadata.reset_index()
   1905 

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2712                     should_rejoin = False
   2713             try:
-> 2714                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2715             finally:
   2716                 for f in futures.values():

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1985             else:
   1986                 local_worker = None
-> 1987             return self.sync(
   1988                 self._gather,
   1989                 futures,

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    831             return future
    832         else:
--> 833             return sync(
    834                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    835             )

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1850                             exc = CancelledError(key)
   1851                         else:
-> 1852                             raise exception.with_traceback(traceback)
   1853                         raise exc
   1854                     if errors == "skip":

~/miniconda3/envs/bsql2/lib/python3.8/site-packages/dask/dataframe/utils.py in check_meta()
    671         )
    672 
--> 673     raise ValueError(
    674         "Metadata mismatch found%s.\n\n"
    675         "%s" % ((" in `%s`" % funcname if funcname else ""), errmsg)

ValueError: Metadata mismatch found in `from_delayed`.
```

I think the metadata ends up with the different schema and therefore bringing it in from different nodes causes issues.
We need to properly handle metadata for columns that are all nulls

### PR DESCRIPTION
**Pull request by Christian8491**
This PR closes #1023

### CODE REVIEW

**Comment by williamBlazing** [comment]
@Christian8491 this change you have here, does indeed make it so that it no longer crashes, but its not enough. What is happening now is that if there is no statistical info for a column and rowgroup, then it does not set the value, which means its left at 0. This means that for this row group, it will think that the min and max are both 0 for that row group, which is incorrect. Now, we dont know what we should set it, so the safe thing to do is to set the min value to the min of that data type and set the max of that value to the max of that type

**Comment by williamBlazing** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun tests

**Pull request merged**
