### PR TITLE
[REVIEW] Support for CONCAT alias operator

### LINKED ISSUE #1138: [FEA] Support CONCAT alias for string concatenation
Today, I can concatenate strings with the `||` operator. For ease of porting existing SQL queries, I'd like to be able to use the `CONCAT` alias as well. In the 2020-11-09 nightlies, it hangs the kernel and prints the `Unsupported operator: CONCAT|||||` RAL error.

```python
from blazingsql import BlazingContext
import cudf
from dask.datasets import timeseries
import pandas as pd
​
bc = BlazingContext()
​
df = pd.DataFrame({
    "a": ["Adele", "James"],
    "b": [10, 9],
    "c": [5, None]
})
​
bc.create_table("df", df)
bc.create_table("df2", df)
​
query = """
SELECT
    'Name: ' || a
FROM df
"""
​
print(bc.explain(query))
print(bc.sql(query))
​
​
query = """
SELECT
    CONCAT('Name: ', a)
FROM df
"""
​
print(bc.explain(query))
print(bc.sql(query)) # hangs
BlazingContext ready
LogicalProject(EXPR$0=[||('Name: ', $0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[EXPR$0]])

        EXPR$0
0  Name: Adele
1  Name: James
LogicalProject(EXPR$0=[CONCAT('Name: ', $0)])
  BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[EXPR$0]])

```

```
conda list | grep blazingsql
blazingsql                0.17.0a         cuda10.2_py37_130    blazingsql-nightly/label/cuda10.2
```

### PR DESCRIPTION
**Pull request by Christian8491**
This PR closes #1138

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Review by felipeblazing — APPROVED** [review]

**Pull request merged**
