### PR TITLE
[WIP] Cast decimal from orc to float64

### PR DESCRIPTION
**Pull request by gcca**
Fixes VDE-289

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by felipeblazing** [comment]
add to allow list

**Comment by felipeblazing** [comment]
run testss

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by ajschmidt8** [comment]
add to allowlist

**Comment by wmalpica** [comment]
rerun tests

**Pull request merged**
