### PR TITLE
[REVIEW] Fix for Column aliases when exists a Join op

### LINKED ISSUE #1393: [BUG] Column aliases are not being applied
**Describe the bug**
In the relational algebra plan generated by Calcite, in some cases, the aliases for columns are not being generated or propagated properly. 

**Steps/Code to reproduce bug**
The following query demonstrates the behavior:
```
select o1.o_orderkey as okey1, o2.o_orderkey as okey2 from orders as o1
                    inner join orders as o2 on o1.o_orderkey = o2.o_orderkey
                    and o1.o_orderkey < 10000
```
Its relational algebra is:
```
LogicalJoin(condition=[=($0, $1)], joinType=[inner])
  BindableTableScan(table=[[main, orders]], filters=[[<($0, 10000)]], projects=[[0]], aliases=[[o_orderkey]])
  BindableTableScan(table=[[main, orders]], projects=[[0]], aliases=[[o_orderkey]])
```

**Expected behavior**
As you can see in the example above, the aliases pushed down to the BindableTableScan are not the aliases provided but are instead the original column names

**----For BlazingSQL Developers----**
**Suspected source of the issue**
This will likely need to be addressed by the Calcite rules

### PR DESCRIPTION
**Pull request by Christian8491**
This PR closes #1393

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Christian8491** [comment]
rerun tests

**Comment by williamBlazing** [comment]
I noticed that the reference result for the calcite unit tests changed. Could you please explain which relational algebras changed, and from what to what?

Also, could you please explain the changes in this PR in general terms. I notice you added two rules. I am assuming these are modified versions of the original calcite rules. Is that correct? If so, can you explain what you did to change or improve those rules?

Finally, one more request, could you please add the offending query to the calcite unit tests queries set. We should be adding queries to that all the time to cover all the interesting cases we encounter where the rules break

**Comment by Christian8491** [comment]
In terms of Performance, this PR does nothing.  About the relational algebras, only the `LogicalProject` now is updated (not due to the number of projected columns or new expressions, just aliases). As a summary, the tpch-plans that were updated are: {2,3,4,5,7,8,9,10,11,12,13,14,15,17,18,19,20,21} so for this reason, the reference result had to be updated. 

About changes, The `ProjectJoinTransposeRule.java` file  as you mention is based on the original version but this one creates a new function called `createProjectRefsAndExprsCustomized()` that save the aliases of Projects before transposing with a LogicalJoin (this step miss the aliases).  

To check out how the new logical plans are updated i will show a couple of these tpch new-logical-plans .

* Query (issue #1393)
```
query = select o1.o_orderkey as okey1, o2.o_orderkey as okey2 from orders as o1
                    inner join orders as o2 on o1.o_orderkey = o2.o_orderkey
                    and o1.o_orderkey < 10000
```

 Plan before this PR: 
```
LogicalJoin(condition=[=($0, $1)], joinType=[inner])
  BindableTableScan(table=[[main, orders]], filters=[[<($0, 10000)]], projects=[[0]], aliases=[[o_orderkey]])
  BindableTableScan(table=[[main, orders]], projects=[[0]], aliases=[[o_orderkey]])
```
          
Plan After this PR
```
LogicalJoin(condition=[=($0, $1)], joinType=[inner])
  BindableTableScan(table=[[main, orders]], filters=[[<($0, 10000)]], projects=[[0]], aliases=[[okey1]])
  BindableTableScan(table=[[main, orders]], projects=[[0]], aliases=[[okey2]])
```

* Tpch-13

Plan Before this PR:
```
LogicalSort(sort0=[$1], sort1=[$0], dir0=[DESC], dir1=[DESC])
  LogicalAggregate(group=[{0}], custdist=[COUNT()])
    LogicalProject(c_count=[$1])
      LogicalAggregate(group=[{0}], EXPR$1=[COUNT($1)])
        LogicalProject(c_custkey=[$0], o_orderkey=[$1])
          LogicalJoin(condition=[=($0, $2)], joinType=[left])
            BindableTableScan(table=[[main, customer]], projects=[[0]], aliases=[[c_custkey]])
            LogicalProject(o_orderkey=[$0], o_custkey=[$1])
              BindableTableScan(table=[[main, orders]], filters=[[NOT(LIKE($2, '%special%requests%'))]], projects=[[0, 1, 8]], aliases=[[o_orderkey, o_custkey, $f2]])
```

Plan after this PR:
```
LogicalSort(sort0=[$1], sort1=[$0], dir0=[DESC], dir1=[DESC])
  LogicalAggregate(group=[{0}], custdist=[COUNT()])
    LogicalProject(c_count=[$1])
      LogicalAggregate(group=[{0}], EXPR$1=[COUNT($1)])
        LogicalProject(c_custkey=[$0], o_orderkey=[$1])
          LogicalJoin(condition=[=($0, $2)], joinType=[left])
            BindableTableScan(table=[[main, customer]], projects=[[0]], aliases=[[c_custkey]])
            LogicalProject(o_orderkey=[$0], $f1=[$1])
              BindableTableScan(table=[[main, orders]], filters=[[NOT(LIKE($2, '%special%requests%'))]], projects=[[0, 1, 8]], aliases=[[o_orderkey, $f1, $f2]])
```

* Tpch-17

Plan before this PR:
```
LogicalProject(avg_yearly=[/($0, 7.0:DECIMAL(2, 1))])
  LogicalProject($f0=[CASE(=($1, 0), null:DOUBLE, $0)])
    LogicalAggregate(group=[{}], agg#0=[$SUM0($0)], agg#1=[COUNT($0)])
      LogicalProject(l_extendedprice=[$1])
        LogicalJoin(condition=[AND(=($2, $3), <($0, $4))], joinType=[inner])
          LogicalProject(l_quantity=[$1], l_extendedprice=[$2], p_partkey=[$3])
            LogicalJoin(condition=[=($3, $0)], joinType=[inner])
              BindableTableScan(table=[[main, lineitem]], projects=[[1, 4, 5]], aliases=[[l_partkey, l_quantity, l_extendedprice]])
              LogicalProject(p_partkey=[$0])
                BindableTableScan(table=[[main, part]], filters=[[AND(=($1, 'Brand#23'), =($2, 'MED BOX'))]], projects=[[0, 3, 6]], aliases=[[p_partkey, $f1, $f2]])
          LogicalProject(l_partkey=[$0], *=[*(0.2:DECIMAL(2, 1), $1)])
            LogicalProject(l_partkey=[$0], $f1=[/($1, $2)])
              LogicalProject(l_partkey=[$0], $f1=[CASE(=($2, 0), null:DOUBLE, $1)], $f2=[$2])
                LogicalAggregate(group=[{0}], agg#0=[$SUM0($1)], agg#1=[COUNT($1)])
                  BindableTableScan(table=[[main, lineitem]], filters=[[IS NOT NULL($0)]], projects=[[1, 4]], aliases=[[l_partkey, l_quantity]])
```

Plan after this PR:
```
LogicalProject(avg_yearly=[/($0, 7.0:DECIMAL(2, 1))])
  LogicalProject($f0=[CASE(=($1, 0), null:DOUBLE, $0)])
    LogicalAggregate(group=[{}], agg#0=[$SUM0($0)], agg#1=[COUNT($0)])
      LogicalProject(l_extendedprice=[$1])
        LogicalJoin(condition=[AND(=($2, $3), <($0, $4))], joinType=[inner])
          LogicalProject($f0=[$1], l_extendedprice=[$2], $f2=[$3])
            LogicalJoin(condition=[=($3, $0)], joinType=[inner])
              BindableTableScan(table=[[main, lineitem]], projects=[[1, 4, 5]], aliases=[[$f0, $f01, l_extendedprice]])
              LogicalProject($f2=[$0])
                BindableTableScan(table=[[main, part]], filters=[[AND(=($1, 'Brand#23'), =($2, 'MED BOX'))]], projects=[[0, 3, 6]], aliases=[[$f2, $f1, $f3]])
          LogicalProject($f0=[$0], *=[*(0.2:DECIMAL(2, 1), $1)])
            LogicalProject(l_partkey=[$0], $f1=[/($1, $2)])
              LogicalProject(l_partkey=[$0], $f1=[CASE(=($2, 0), null:DOUBLE, $1)], $f2=[$2])
                LogicalAggregate(group=[{0}], agg#0=[$SUM0($1)], agg#1=[COUNT($1)])
                  BindableTableScan(table=[[main, lineitem]], filters=[[IS NOT NULL($0)]], projects=[[1, 4]], aliases=[[l_partkey, l_quantity]])
```

I have to admit that in some cases the `BindabletableScan` are losing the original aliases. This is something that I think we are not going to want. So I  think have to dig a little deeper.

**Comment by williamBlazing** [comment]
It is a little strange that the purpose of this PR and its changes to rules is to make sure that aliases are properly pushed down to the TableScan, which it does successfully in the troublesome case that inspired this PR. But at the same time in some cases the original aliases are getting lost. It seems like in those cases its not cases where it actually matters for the end result.
Could you please spend a little more time trying to understand why this is happening to see how concerned we should be?
Also, in the code where we are adding/modifying the rules, could you please reference this PR and the issue, so that if we find the need to modify the rules again, or if we find issues with aliases again, we can hopefully quickly look at these changes.

**Comment by Christian8491** [comment]
After these last commits, as a summary, the tpch-plans (reference file)  that were updated are: {7,15,21}. Changes are very tiny in the `LogicalProject` plan, for instance:
* tpch query 15

Before this PR 
```
LogicalSort(sort0=[$0], dir0=[ASC])
  LogicalProject(s_suppkey=[$0], s_name=[$1], s_address=[$2], s_phone=[$3], total_revenue=[$4])
    LogicalJoin(condition=[=($4, $5)], joinType=[inner])
      LogicalProject(s_suppkey=[$0], s_name=[$1], s_address=[$2], s_phone=[$3], EXPR$1=[$5])
        LogicalJoin(condition=[=($0, $4)], joinType=[inner])
          BindableTableScan(table=[[main, supplier]], projects=[[0, 1, 2, 4]], aliases=[[s_suppkey, s_name, s_address, s_phone]])
          LogicalProject(l_suppkey=[$0], EXPR$1=[$1])
            LogicalProject(l_suppkey=[$0], EXPR$1=[CASE(=($2, 0), null:DOUBLE, $1)])
              LogicalAggregate(group=[{0}], EXPR$1=[$SUM0($1)], agg#1=[COUNT($1)])
                LogicalProject(l_suppkey=[$0], $f1=[*($1, -(1, $2))])
                  BindableTableScan(table=[[main, lineitem]], filters=[[AND(>=($3, 1996-01-01 00:00:00), <($3, 1996-04-01 00:00:00))]], projects=[[2, 5, 6, 10]], aliases=[[l_suppkey, l_extendedprice, l_discount, l_shipdate]])
      LogicalProject(EXPR$0=[$0])
        LogicalAggregate(group=[{}], EXPR$0=[MAX($0)])
          LogicalProject(EXPR$1=[$1])
            LogicalProject(l_suppkey=[$0], EXPR$1=[CASE(=($2, 0), null:DOUBLE, $1)])
              LogicalAggregate(group=[{0}], EXPR$1=[$SUM0($1)], agg#1=[COUNT($1)])
                LogicalProject(l_suppkey=[$0], $f1=[*($1, -(1, $2))])
                  BindableTableScan(table=[[main, lineitem]], filters=[[AND(>=($3, 1996-01-01 00:00:00), <($3, 1996-04-01 00:00:00))]], projects=[[2, 5, 6, 10]], aliases=[[l_suppkey, l_extendedprice, l_discount, l_shipdate]])
```

Aftet this PR 
```
LogicalSort(sort0=[$0], dir0=[ASC])
  LogicalProject(s_suppkey=[$0], s_name=[$1], s_address=[$2], s_phone=[$3], total_revenue=[$4])
    LogicalJoin(condition=[=($4, $5)], joinType=[inner])
      LogicalProject(s_suppkey=[$0], s_name=[$1], s_address=[$2], s_phone=[$3], total_revenue=[$5])
        LogicalJoin(condition=[=($0, $4)], joinType=[inner])
          BindableTableScan(table=[[main, supplier]], projects=[[0, 1, 2, 4]], aliases=[[s_suppkey, s_name, s_address, s_phone]])
          LogicalProject(l_suppkey=[$0], total_revenue=[$1])
            LogicalProject(l_suppkey=[$0], EXPR$1=[CASE(=($2, 0), null:DOUBLE, $1)])
              LogicalAggregate(group=[{0}], EXPR$1=[$SUM0($1)], agg#1=[COUNT($1)])
                LogicalProject(l_suppkey=[$0], $f1=[*($1, -(1, $2))])
                  BindableTableScan(table=[[main, lineitem]], filters=[[AND(>=($3, 1996-01-01 00:00:00), <($3, 1996-04-01 00:00:00))]], projects=[[2, 5, 6, 10]], aliases=[[l_suppkey, l_extendedprice, l_discount, l_shipdate]])
      LogicalProject(EXPR$0=[$0])
        LogicalAggregate(group=[{}], EXPR$0=[MAX($0)])
          LogicalProject(EXPR$1=[$1])
            LogicalProject(l_suppkey=[$0], EXPR$1=[CASE(=($2, 0), null:DOUBLE, $1)])
              LogicalAggregate(group=[{0}], EXPR$1=[$SUM0($1)], agg#1=[COUNT($1)])
                LogicalProject(l_suppkey=[$0], $f1=[*($1, -(1, $2))])
                  BindableTableScan(table=[[main, lineitem]], filters=[[AND(>=($3, 1996-01-01 00:00:00), <($3, 1996-04-01 00:00:00))]], projects=[[2, 5, 6, 10]], aliases=[[l_suppkey, l_extendedprice, l_discount, l_shipdate]])
```

Additionally added a couple of comments whether we found out in the future issues related with aliases. 

Finally, added the troublesome query as a new unit test to track it.

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

**Pull request merged**
