### PR TITLE
[REVIEW] Updating rmm header, fixing e2e tests with deprecated drop_column function and fixing ORC args changes

### PR DESCRIPTION
**Pull request by rommelDB**
- Fix for building issues after updating the last rmm.
- Fix for columnBasisTest due to drop_column() is now deprecated.
- Fix for Orc arg changes.

### CODE REVIEW

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by romeluko** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by romeluko** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun tests

**Pull request merged**
