### PR TITLE
[REVIEW] Allow to create tables from compressed files

### LINKED ISSUE #99: Be able to create a blazing table from compressed csv files
Would like to be able to specify compressoin like one can in cudf.read_csv

**Describe alternatives you've considered**
calling read_csv directly then creating a table but this is complicated and uses more memory in case the query only requires a few columns

### PR DESCRIPTION
**Pull request by jeanp413**
Fixes #99

Example:

```python
customerColNames = ["c_custkey", "c_name", "c_address", "c_nationkey", "c_phone", "c_acctbal", "c_mktsegment", "c_comment"]
customerColTypes = ["int32", "str", "str", "int32", "str", "float64", "str", "str"]
bc.create_table('orders', ["compressed_file.gz"], delimiter='|', dtype=customerColTypes, names=customerColNames, file_format="csv", compression='gzip')
```

### CODE REVIEW

**Comment by williamBlazing** [comment]
Does this work even for files in S3?

**Comment by jeanp413** [comment]
I have not test that but it should work, do you have any s3 credentials with a compressed file in a bucket so I can test it?

**Comment by roaramburu** [comment]
@jeanp413 do you still need this test?

We have many public buckets that you can test on.

Here is a zip file on a public s3 bucket you can query now:
bc.s3('blazingsql-colab', bucket_name='blazingsql-colab')
bc.create_table('lineitem', 's3://blazingsql-colab/compression_test/lineitem.zip')

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by williamBlazing** [comment]
rerun-tests

**Review by williamBlazing — APPROVED** [review]

**Pull request merged**
