### PR TITLE
[REVIEW] Throwing an error message when trying to open a directory with wildcards

### PR DESCRIPTION
**Pull request by rommelDB**
Deal with the unexpected crash on #857

### CODE REVIEW

**Comment by rommelDB** [comment]
return tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by rommelDB** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun-tests

**Review by williamBlazing — APPROVED** [review]

**Review by felipeblazing — APPROVED** [review]

**Pull request merged**
